import http.server
import socketserver
from urllib.parse import urlparse
from urllib.parse import parse_qs
import http.client
import json


def asd():
    add = []

    conn = http.client.HTTPSConnection("www.random.org")
    conn.request("GET", "/integers/?num=1&min=1&max=200&col=1&base=10&format=plain&rnd=new")
    add.append(int(conn.getresponse().read().decode()))
    print(add[0])

    conn = http.client.HTTPSConnection("csrng.net")
    conn.request("GET", "/csrng/csrng.php?min=10&max=100")
    data = conn.getresponse().read().decode()
    add.append(int(data[-4:-2]))
    print(add[1])


    conn = http.client.HTTPSConnection("simplecalculatorbygkservice.herokuapp.com")
    conn.request("GET", f'/api/agritaskcalculator/result/{add[0] + add[1]}')
    add.append(conn.getresponse().read().decode())
    print(add[2])
    return add


class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        aux = asd()

        # Some custom HTML code, possibly generated by another function
        html = f"<html>" \
               f"<head>" \
               f"</head>" \
               f"<body>" \
               f"<h1>Your first number is {aux[0]}</h1>" \
               f"<h1>Your second number is {aux[1]}</h1>" \
               f"<h1>Result is {aux[2]}</h1>" \
               f"</body>" \
               f"</html>"\

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8000
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()